#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "/bin/sh" ]; then
  exec "/bin/sh"  C:/Users/roryw/AppData/Roaming/xPacks/@xpack-dev-tools/arm-none-eabi-gcc/11.2.1-1.1.1/.content/bin/arm-none-eabi-gdb-add-index "$@"
else 
  exec /bin/sh  C:/Users/roryw/AppData/Roaming/xPacks/@xpack-dev-tools/arm-none-eabi-gcc/11.2.1-1.1.1/.content/bin/arm-none-eabi-gdb-add-index "$@"
fi
