#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
esac

exec "C:/Users/roryw/AppData/Roaming/xPacks/@xpack-dev-tools/windows-build-tools/4.3.0-1.1/.content/bin/make.exe"   "$@"
